CC=g++

PROGRAMS= test1 test2 test3 test4 test5 test6 test7 test8

ALL: $(PROGRAMS)

test1: test1.cpp
	$(CC) test1.cpp -o test1 -lstreaming -g -O0
	
test2: test2.cpp
	$(CC) test2.cpp -o test2 -lstreaming -g -O0
	
test3: test3.cpp
	$(CC) test3.cpp -o test3 -lstreaming -g -O0
	
test4: test4.cpp
	$(CC) test4.cpp -o test4 -lstreaming -g -O0
	
test5: test5.cpp
	$(CC) test5.cpp -o test5 -lstreaming -g -O0
	
test6: test6.cpp
	$(CC) test6.cpp -o test6 -lstreaming -g -O0
	
test7: test7.cpp
	$(CC) test7.cpp -o test7 -lstreaming -g -O0
	
test8: test8.cpp
	$(CC) test8.cpp -o test8 -lstreaming -g -O0
	
clean:
	rm -f $(PROGRAMS)
	

