CC=g++

PROGRAMS= test1 test2 test3 test4 videoFileToFileTest screenshotTest test7 test8

ALL: $(PROGRAMS)

test1: test1.cpp
	$(CC) test1.cpp -o test1 -lavenconding -g -O0
	
test2: test2.cpp
	$(CC) test2.cpp -o test2 -lavenconding -g -O0
	
test3: test3.cpp
	$(CC) test3.cpp -o test3 -lavenconding -g -O0
	
test4: test4.cpp
	$(CC) test4.cpp -o test4 -lavenconding -g -O0
	
videoFileToFileTest: videoFileToFileTest.cpp
	$(CC) videoFileToFileTest.cpp -o videoFileToFileTest -lavenconding -g -O0
	
screenshotTest: screenshotTest.cpp
	$(CC) screenshotTest.cpp -o screenshotTest -lavenconding -lcpputil -g -O0
	
test7: test7.cpp
	$(CC) test7.cpp -o test7 -lavenconding -g -O0
	
test8: test8.cpp
	$(CC) test8.cpp -o test8 -lavenconding -g -O0
	
clean:
	rm -f $(PROGRAMS)
	

