/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class br_ufscar_lince_streaming_ImageShotter */

#ifndef _Included_br_ufscar_lince_streaming_ImageShotter
#define _Included_br_ufscar_lince_streaming_ImageShotter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     br_ufscar_lince_streaming_ImageShotter
 * Method:    takeShot
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_br_ufscar_lince_streaming_ImageShotter_takeShot__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     br_ufscar_lince_streaming_ImageShotter
 * Method:    takeShot
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_br_ufscar_lince_streaming_ImageShotter_takeShot__Ljava_lang_String_2I
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     br_ufscar_lince_streaming_ImageShotter
 * Method:    takeShot
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_br_ufscar_lince_streaming_ImageShotter_takeShot__Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     br_ufscar_lince_streaming_ImageShotter
 * Method:    setImageSize
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_br_ufscar_lince_streaming_ImageShotter_setImageSize
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     br_ufscar_lince_streaming_ImageShotter
 * Method:    getImageWidht
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_br_ufscar_lince_streaming_ImageShotter_getImageWidht
  (JNIEnv *, jobject);

/*
 * Class:     br_ufscar_lince_streaming_ImageShotter
 * Method:    getImageHeight
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_br_ufscar_lince_streaming_ImageShotter_getImageHeight
  (JNIEnv *, jobject);

/*
 * Class:     br_ufscar_lince_streaming_ImageShotter
 * Method:    doSetImageCodec
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_br_ufscar_lince_streaming_ImageShotter_doSetImageCodec
  (JNIEnv *, jobject, jint);

/*
 * Class:     br_ufscar_lince_streaming_ImageShotter
 * Method:    setImageCodec
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_br_ufscar_lince_streaming_ImageShotter_setImageCodec
  (JNIEnv *, jobject, jstring);

/*
 * Class:     br_ufscar_lince_streaming_ImageShotter
 * Method:    waitFinishing
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_br_ufscar_lince_streaming_ImageShotter_waitFinishing
  (JNIEnv *, jobject);

/*
 * Class:     br_ufscar_lince_streaming_ImageShotter
 * Method:    isFinished
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_br_ufscar_lince_streaming_ImageShotter_isFinished
  (JNIEnv *, jobject);

/*
 * Class:     br_ufscar_lince_streaming_ImageShotter
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_br_ufscar_lince_streaming_ImageShotter_destroy
  (JNIEnv *, jobject);

/*
 * Class:     br_ufscar_lince_streaming_ImageShotter
 * Method:    create
 * Signature: (Lbr/ufscar/lince/streaming/AVSource;)J
 */
JNIEXPORT jlong JNICALL Java_br_ufscar_lince_streaming_ImageShotter_create
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
