/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class br_ufscar_lince_streaming_X11Terminal */

#ifndef _Included_br_ufscar_lince_streaming_X11Terminal
#define _Included_br_ufscar_lince_streaming_X11Terminal
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     br_ufscar_lince_streaming_X11Terminal
 * Method:    getFormat
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_br_ufscar_lince_streaming_X11Terminal_getFormat
  (JNIEnv *, jobject);

/*
 * Class:     br_ufscar_lince_streaming_X11Terminal
 * Method:    getWidth
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_br_ufscar_lince_streaming_X11Terminal_getWidth
  (JNIEnv *, jobject);

/*
 * Class:     br_ufscar_lince_streaming_X11Terminal
 * Method:    getHeight
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_br_ufscar_lince_streaming_X11Terminal_getHeight
  (JNIEnv *, jobject);

/*
 * Class:     br_ufscar_lince_streaming_X11Terminal
 * Method:    getFps
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_br_ufscar_lince_streaming_X11Terminal_getFps
  (JNIEnv *, jobject);

/*
 * Class:     br_ufscar_lince_streaming_X11Terminal
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_br_ufscar_lince_streaming_X11Terminal_destroy
  (JNIEnv *, jobject);

/*
 * Class:     br_ufscar_lince_streaming_X11Terminal
 * Method:    create
 * Signature: (III)J
 */
JNIEXPORT jlong JNICALL Java_br_ufscar_lince_streaming_X11Terminal_create
  (JNIEnv *, jobject, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
