/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class br_ufscar_lince_streaming_AVInputFile */

#ifndef _Included_br_ufscar_lince_streaming_AVInputFile
#define _Included_br_ufscar_lince_streaming_AVInputFile
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     br_ufscar_lince_streaming_AVInputFile
 * Method:    getFilename
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_br_ufscar_lince_streaming_AVInputFile_getFilename
  (JNIEnv *, jobject);

/*
 * Class:     br_ufscar_lince_streaming_AVInputFile
 * Method:    getFormat
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_br_ufscar_lince_streaming_AVInputFile_getFormat
  (JNIEnv *, jobject);

/*
 * Class:     br_ufscar_lince_streaming_AVInputFile
 * Method:    create
 * Signature: (Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_br_ufscar_lince_streaming_AVInputFile_create
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     br_ufscar_lince_streaming_AVInputFile
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_br_ufscar_lince_streaming_AVInputFile_destroy
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
