/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class br_ufscar_lince_streaming_AVEncoder */

#ifndef _Included_br_ufscar_lince_streaming_AVEncoder
#define _Included_br_ufscar_lince_streaming_AVEncoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     br_ufscar_lince_streaming_AVEncoder
 * Method:    setVideoBitrate
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_br_ufscar_lince_streaming_AVEncoder_setVideoBitrate
  (JNIEnv *, jobject, jint);

/*
 * Class:     br_ufscar_lince_streaming_AVEncoder
 * Method:    getVideoBitrate
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_br_ufscar_lince_streaming_AVEncoder_getVideoBitrate
  (JNIEnv *, jobject);

/*
 * Class:     br_ufscar_lince_streaming_AVEncoder
 * Method:    setFramesPerSecond
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_br_ufscar_lince_streaming_AVEncoder_setFramesPerSecond
  (JNIEnv *, jobject, jint);

/*
 * Class:     br_ufscar_lince_streaming_AVEncoder
 * Method:    getFramesPerSecond
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_br_ufscar_lince_streaming_AVEncoder_getFramesPerSecond
  (JNIEnv *, jobject);

/*
 * Class:     br_ufscar_lince_streaming_AVEncoder
 * Method:    setAspectRatio
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_br_ufscar_lince_streaming_AVEncoder_setAspectRatio
  (JNIEnv *, jobject, jstring);

/*
 * Class:     br_ufscar_lince_streaming_AVEncoder
 * Method:    setVideoSize
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_br_ufscar_lince_streaming_AVEncoder_setVideoSize__II
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     br_ufscar_lince_streaming_AVEncoder
 * Method:    setVideoSize
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_br_ufscar_lince_streaming_AVEncoder_setVideoSize__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     br_ufscar_lince_streaming_AVEncoder
 * Method:    getVideoWidht
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_br_ufscar_lince_streaming_AVEncoder_getVideoWidht
  (JNIEnv *, jobject);

/*
 * Class:     br_ufscar_lince_streaming_AVEncoder
 * Method:    getVideoHeight
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_br_ufscar_lince_streaming_AVEncoder_getVideoHeight
  (JNIEnv *, jobject);

/*
 * Class:     br_ufscar_lince_streaming_AVEncoder
 * Method:    setVideoCodec
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_br_ufscar_lince_streaming_AVEncoder_setVideoCodec
  (JNIEnv *, jobject, jstring);

/*
 * Class:     br_ufscar_lince_streaming_AVEncoder
 * Method:    setAudioSamplingRate
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_br_ufscar_lince_streaming_AVEncoder_setAudioSamplingRate
  (JNIEnv *, jobject, jint);

/*
 * Class:     br_ufscar_lince_streaming_AVEncoder
 * Method:    getAudioSamplingRate
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_br_ufscar_lince_streaming_AVEncoder_getAudioSamplingRate
  (JNIEnv *, jobject);

/*
 * Class:     br_ufscar_lince_streaming_AVEncoder
 * Method:    setAudioBitrate
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_br_ufscar_lince_streaming_AVEncoder_setAudioBitrate
  (JNIEnv *, jobject, jint);

/*
 * Class:     br_ufscar_lince_streaming_AVEncoder
 * Method:    getAudioBitrate
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_br_ufscar_lince_streaming_AVEncoder_getAudioBitrate
  (JNIEnv *, jobject);

/*
 * Class:     br_ufscar_lince_streaming_AVEncoder
 * Method:    setAudioChannelsNumber
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_br_ufscar_lince_streaming_AVEncoder_setAudioChannelsNumber
  (JNIEnv *, jobject, jint);

/*
 * Class:     br_ufscar_lince_streaming_AVEncoder
 * Method:    getAudioChannelsNumber
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_br_ufscar_lince_streaming_AVEncoder_getAudioChannelsNumber
  (JNIEnv *, jobject);

/*
 * Class:     br_ufscar_lince_streaming_AVEncoder
 * Method:    setAudioCodec
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_br_ufscar_lince_streaming_AVEncoder_setAudioCodec
  (JNIEnv *, jobject, jstring);

/*
 * Class:     br_ufscar_lince_streaming_AVEncoder
 * Method:    setThreadsNumber
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_br_ufscar_lince_streaming_AVEncoder_setThreadsNumber
  (JNIEnv *, jobject, jint);

/*
 * Class:     br_ufscar_lince_streaming_AVEncoder
 * Method:    getThreadsNumber
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_br_ufscar_lince_streaming_AVEncoder_getThreadsNumber
  (JNIEnv *, jobject);

/*
 * Class:     br_ufscar_lince_streaming_AVEncoder
 * Method:    setVideoPreset
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_br_ufscar_lince_streaming_AVEncoder_setVideoPreset
  (JNIEnv *, jobject, jstring);

/*
 * Class:     br_ufscar_lince_streaming_AVEncoder
 * Method:    setAudioPreset
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_br_ufscar_lince_streaming_AVEncoder_setAudioPreset
  (JNIEnv *, jobject, jstring);

/*
 * Class:     br_ufscar_lince_streaming_AVEncoder
 * Method:    getVideoPreset
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_br_ufscar_lince_streaming_AVEncoder_getVideoPreset
  (JNIEnv *, jobject);

/*
 * Class:     br_ufscar_lince_streaming_AVEncoder
 * Method:    getAudioPreset
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_br_ufscar_lince_streaming_AVEncoder_getAudioPreset
  (JNIEnv *, jobject);

/*
 * Class:     br_ufscar_lince_streaming_AVEncoder
 * Method:    setPropertyValue
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_br_ufscar_lince_streaming_AVEncoder_setPropertyValue
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     br_ufscar_lince_streaming_AVEncoder
 * Method:    getPropertyValue
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_br_ufscar_lince_streaming_AVEncoder_getPropertyValue
  (JNIEnv *, jobject, jstring);

/*
 * Class:     br_ufscar_lince_streaming_AVEncoder
 * Method:    enableCopyVideo
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_br_ufscar_lince_streaming_AVEncoder_enableCopyVideo
  (JNIEnv *, jobject);

/*
 * Class:     br_ufscar_lince_streaming_AVEncoder
 * Method:    enableCopyAudio
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_br_ufscar_lince_streaming_AVEncoder_enableCopyAudio
  (JNIEnv *, jobject);

/*
 * Class:     br_ufscar_lince_streaming_AVEncoder
 * Method:    create
 * Signature: (Lbr/ufscar/lince/streaming/AVSource;)J
 */
JNIEXPORT jlong JNICALL Java_br_ufscar_lince_streaming_AVEncoder_create__Lbr_ufscar_lince_streaming_AVSource_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     br_ufscar_lince_streaming_AVEncoder
 * Method:    create
 * Signature: (Lbr/ufscar/lince/streaming/AVEncoder;)J
 */
JNIEXPORT jlong JNICALL Java_br_ufscar_lince_streaming_AVEncoder_create__Lbr_ufscar_lince_streaming_AVEncoder_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     br_ufscar_lince_streaming_AVEncoder
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_br_ufscar_lince_streaming_AVEncoder_destroy
  (JNIEnv *, jobject);

/*
 * Class:     br_ufscar_lince_streaming_AVEncoder
 * Method:    doSetVideoCodec
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_br_ufscar_lince_streaming_AVEncoder_doSetVideoCodec
  (JNIEnv *, jobject, jint);

/*
 * Class:     br_ufscar_lince_streaming_AVEncoder
 * Method:    doSetAspectRatio
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_br_ufscar_lince_streaming_AVEncoder_doSetAspectRatio
  (JNIEnv *, jobject, jint);

/*
 * Class:     br_ufscar_lince_streaming_AVEncoder
 * Method:    doSetAudioCodec
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_br_ufscar_lince_streaming_AVEncoder_doSetAudioCodec
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
