/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class br_ufscar_lince_streaming_SharedBuffer */

#ifndef _Included_br_ufscar_lince_streaming_SharedBuffer
#define _Included_br_ufscar_lince_streaming_SharedBuffer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     br_ufscar_lince_streaming_SharedBuffer
 * Method:    getFormat
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_br_ufscar_lince_streaming_SharedBuffer_getFormat
  (JNIEnv *, jobject);

/*
 * Class:     br_ufscar_lince_streaming_SharedBuffer
 * Method:    getWidth
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_br_ufscar_lince_streaming_SharedBuffer_getWidth
  (JNIEnv *, jobject);

/*
 * Class:     br_ufscar_lince_streaming_SharedBuffer
 * Method:    getHeight
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_br_ufscar_lince_streaming_SharedBuffer_getHeight
  (JNIEnv *, jobject);

/*
 * Class:     br_ufscar_lince_streaming_SharedBuffer
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_br_ufscar_lince_streaming_SharedBuffer_destroy
  (JNIEnv *, jobject);

/*
 * Class:     br_ufscar_lince_streaming_SharedBuffer
 * Method:    create
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_br_ufscar_lince_streaming_SharedBuffer_create
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
